# Generated by Django 5.1.1 on 2025-03-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_super_link_tag_club_event_project_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
