# Generated by Django 5.1.6 on 2025-03-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_users_super_followers_comment_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
