# Generated by Django 5.1.1 on 2025-03-23 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_club_post_event_post_misc_post_project_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='followers',
            field=models.ManyToManyField(related_name='super_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
